### ISSUE TITLE
object-hash manipulates/alters the informed string before hashing it and generates an unexpected hash

### ISSUE THREAD

**Issue by jweyrich** [puleos/object-hash#104]
Why do you "manipulate" the information that's going to be hashed and do not use the original string only?

Currently, your string hashing does the following ([see here](https://github.com/puleos/object-hash/blob/9991b54f2b71c5e88d5534f15499c93dc49bc68b/index.js#L305)):

    _string: function(string){
      write('string:' + string.length + ':');
      write(string.toString());
    },

If someone uses your lib believing (s)he is hashing the informed string and that it could be compared to a hash generated in another program/language, then (s)he might run into problems. We just did.
We have 2 different applications using the a generated hash as PK on a DynamoDB table, and the values weren't matching. So I went to debug and just found that you're manipulating the informed string before hashing it.

PLEASE, add a notice about this behaviour in your docs.

**Comment by addaleax** [comment]
> Why do you "manipulate" the information that's going to be hashed and do not use the original string only?

Because that would break the cryptographic hashing property – there is no way to ensure that the hash for an object does not conflict with the hash for the corresponding string if we didn’t manipulate it.

> If someone uses your lib believing (s)he is hashing the informed string and that it could be compared to a hash generated in another program/language, then (s)he might run into problems. We just did.

- If you’re hashing strings only, this is the *wrong* library for it. This is about hashing JS objects and values, not strings, as the readme states.
- If you’re hashing objects, you’re not going to get results that are comparable with other programming languages either way.

> PLEASE, add a notice about this behaviour in your docs.

PRs are welcome.

**Comment by jweyrich** [comment]
> Because that would break the cryptographic hashing property – there is no way to ensure that the hash for an object does not conflict with the hash for the corresponding string if we didn’t manipulate it.

Collision rate is most likely not improved by prefixing the original string. Representing any amount of data in a few bytes will cause collisions eventually.

Point taken. We've moved to pure crypto.

**Comment by addaleax** [comment]
> > Because that would break the cryptographic hashing property – there is no way to ensure that the hash for an object does not conflict with the hash for the corresponding string if we didn’t manipulate it.
> 
> Collision rate is most likely not improved by prefixing the original string. Representing any amount of data in a few bytes will cause collisions eventually.

That’s not the point – the point is that we need to serialize objects to byte sequences in some way in order to hash them, but we also need to differentiate them from user input that represents that exact byte sequence as a string. For example, if `objectHash({ a: 1 })` were to be implemented naïvely as `hash(JSON.stringify({ a: 1 }))`, then `objectHash({ a: 1 }) === objectHash('{"a":1}')`, and that would be *bad*, because cryptographic hash functions should make it infeasible to generate two inputs with the same hash.

**Comment by jweyrich** [comment]
You can use any arbitrary format/sequence you want.
My concern is that the library provides an interface that allows strings to be hashed, and the hash is not generated based purely on the provided string, but rather over a sequence of different bytes. If this makes sense to this library, it's OK, but IMHO, this behaviour should be clearly stated in the docs.
