### ISSUE TITLE
Hashing closures

### ISSUE THREAD

**Issue by koraa** [puleos/object-hash#21]
It should be possible to hash closure functions;

As an example:
```
function proxyFunction(function f) {
  return function() {
    f.apply(this, arguments);
  };
}

var a = proxyFunction(function() { return 42; });
var b = proxyFunction(function() { return 23; });

assert(hash(a) === hash(b));
```

Even though the functions are actually different, their hash would be the same, since both would generate the string: `function() { f.apply(this, arguments }` (or something similar).
At least on V8.

The best way to solve that would be hashing based on the scope: `a` and `b` both have a variable `f` in their scope and actually use it. This variable is what makes the difference between `a` and `b`, so it would be cool if we could incorporate that into the hash.

Of course. JS doesn't allow this.

As a workaround with my `types-and-functions` branch, the proxyFunction could store it's arguments as a property on the generated function, but that's not really nice.

I don't know how to solve this well, but maybe someone else can think of something.

**Comment by addaleax** [comment]
Given that only `a` is available to the hash function and only very few properties of functions are available, I don’t think this can be done – your workaround is the best thing that comes to my mind. I don’t know if there’s anything more available than which is listed by the tab completion of the node.js/io.js CLI when typing in `a.[TAB]`, but none of the possibilities there seem to lead anywhere interesting.

Hashing based on the scope does not look very possible anyway, since the JS engine can implement passing of variables to closures in any way it wants to. For example, it seems to me that V8 will optimize out unused variables, and probably do similar things for values which are known to be constant, etc. You can pass `--print_code --print_opt_code` to node.js/io.js yourself, if you want to take a look – the output seems quite interesting to me, thanks for making me curious! ;)

Also, the variables which are passed in might be modified by the function, e.g. if one checks object contents rather than object identity (which is this module’s purpose), one could have:
```js
function proxy(obj) {
    return function() {
        obj.counter++;
    }
}

var a = proxy({counter: 1});
var b = proxy({counter: 0});

assert.notEqual(hash(a), hash(b));
b();
assert.equal   (hash(a), hash(b));
a();
assert.notEqual(hash(a), hash(b));
```

I can definitely see your motivation for this and would love to see it implemented in some way, but I’m afraid there’s not much one can do about it. :/

And just btw, you can start your inline code in markdown with ``` ``​`js ``` (or analogues for other languages) to get syntax highlighting, at least here on github.
