### ISSUE TITLE
How i can get back my hashed object?

### ISSUE THREAD

**Issue by AliSultanKhan** [puleos/object-hash#83]
For Example, I Have This Code 

`var peter = {name: 'Peter', stapler: false, friends: ['Joanna', 'Michael', 'Samir'] };`
 `var newObj = hash(peter);`
`console.log(hash(newObj));`

when i log i get // ea704904848c6d8a81571ff280efaf99a48b76e6

Now I want this object again its original condition for further use. 
Original state : {name: 'Peter', stapler: false, friends: ['Joanna', 'Michael', 'Samir'] };

**Comment by addaleax** [comment]
This is impossible by design – hashes are one-way functions, meaning that the results cannot be used to reconstruct the original data.

If you do need to retrieve the original data based on the hash, you need to store the original object separately, or used a full serialization API that allows you to restored the object to its original state from a string representation.
